#!/usr/bin/env bash
# Bash script that transfers a file from client to a server

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path_to_file=$1
ip_address=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$ip_address":~
