#!/bin/bash
# A Bash script that configures a new Ubuntu machine

# Update Ubuntu packages
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
