#!/bin/bash
# A Bash script that configures a new Ubuntu machine

# Update Ubuntu packages
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Set Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
