#!/bin/bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.
# The redirection must be a “301 Moved Permanently"

# Step 1: Install Nginx web server
apt-get update
apt-get install -y nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Step 2: Configure the redirect
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Add other server blocks for your website here
}" > /etc/nginx/sites-available/default

# Step 3: Restart Nginx
systemctl restart nginx

