#!/usr/bin/env bash
# Setup haproxy on a new server
sudo apt update
sudo apt -y install haproxy

# Make sure that HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Listen to web1 and web2 servers
 echo "
	frontend http-in
    		bind *:80
    		mode http
    		default_backend servers
		listen load_balancer
		bind *:80
		mode http
		option httpclose
		option forwardfor
      
      
	backend servers
    		mode http
    		balance roundrobin
   server 183504-web-01 54.196.42.98:80 check
   server 183504-web-02 54.167.174.125:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
sudo systemctl start haproxy
