#!/usr/bin/env bash
88s-yta-hm6
# Path parameters
export dashboard_id="CHANGE_ME"
# Curl command
curl -X GET "https://api.datadoghq.com/api/v1/dashboard/${dashboard_id}" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}"
