#!/usr/bin/env bash
# Fixes a web server to run Nginx as Nginx user listening on port 8080
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen\s80/listen 8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service start nginx
