#!/usr/bin/env bash
# Fixes a web server to run Nginx as Nginx user listening on port 8080

sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service start nginx
