#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

if pgrep gunicorn >/dev/null; then
	echo "Reloading Gunicorn gracefully..."
	pkill -HUP gunicorn
	sleep 2
	pgrep gunicorn >/dev/null && echo "Gunicorn reloaded successfully." || echo "Gunicorn failed to reload."
else
	echo "Gunicorn is not running."
	exit 1
fi
